# coding: utf-8

"""
    umd.io

    Welcome to umd.io, the open-source API for University of Maryland data. If you are building a University data-focused app, hack, or project, you’re in the right place. This site will walk you through basic API use and document all supported API calls.  umd.io is a GETful API. It follows RESTful conventions, but for now, you can only get data – you can’t create, update, or destroy.  We're now in version 1! We might add new endpoints or more data to existing responses, but we won't remove anything without a major version change.  If you're looking for the v0 docs, you can find them at https://docs.umd.io/. Please note that v0 is deprecated. It will continue to be supported until at least 2021, but will get no further feature updates, and will eventually be discontinued.  We are actively looking for contributors! Tweet, email, or otherwise get in touch with us.  # noqa: E501

    The version of the OpenAPI document: 1.0.0 Beta
    Contact: hi@umd.io
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from umd_io import schemas  # noqa: F401


class Section(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Represents a single section of a course.
    """


    class MetaOapg:
        
        class properties:
            course = schemas.StrSchema
            section_id = schemas.StrSchema
            semester = schemas.StrSchema
            number = schemas.StrSchema
            seats = schemas.StrSchema
            
            
            class meetings(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['Meeting']:
                        return Meeting
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['Meeting'], typing.List['Meeting']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'meetings':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'Meeting':
                    return super().__getitem__(i)
            open_seats = schemas.StrSchema
            waitlist = schemas.StrSchema
            
            
            class instructors(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    items = schemas.StrSchema
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple[typing.Union[MetaOapg.items, str, ]], typing.List[typing.Union[MetaOapg.items, str, ]]],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'instructors':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> MetaOapg.items:
                    return super().__getitem__(i)
            __annotations__ = {
                "course": course,
                "section_id": section_id,
                "semester": semester,
                "number": number,
                "seats": seats,
                "meetings": meetings,
                "open_seats": open_seats,
                "waitlist": waitlist,
                "instructors": instructors,
            }
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["course"]) -> MetaOapg.properties.course: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["section_id"]) -> MetaOapg.properties.section_id: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["semester"]) -> MetaOapg.properties.semester: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["number"]) -> MetaOapg.properties.number: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["seats"]) -> MetaOapg.properties.seats: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["meetings"]) -> MetaOapg.properties.meetings: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["open_seats"]) -> MetaOapg.properties.open_seats: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["waitlist"]) -> MetaOapg.properties.waitlist: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["instructors"]) -> MetaOapg.properties.instructors: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["course", "section_id", "semester", "number", "seats", "meetings", "open_seats", "waitlist", "instructors", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["course"]) -> typing.Union[MetaOapg.properties.course, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["section_id"]) -> typing.Union[MetaOapg.properties.section_id, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["semester"]) -> typing.Union[MetaOapg.properties.semester, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["number"]) -> typing.Union[MetaOapg.properties.number, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["seats"]) -> typing.Union[MetaOapg.properties.seats, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["meetings"]) -> typing.Union[MetaOapg.properties.meetings, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["open_seats"]) -> typing.Union[MetaOapg.properties.open_seats, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["waitlist"]) -> typing.Union[MetaOapg.properties.waitlist, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["instructors"]) -> typing.Union[MetaOapg.properties.instructors, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["course", "section_id", "semester", "number", "seats", "meetings", "open_seats", "waitlist", "instructors", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        course: typing.Union[MetaOapg.properties.course, str, schemas.Unset] = schemas.unset,
        section_id: typing.Union[MetaOapg.properties.section_id, str, schemas.Unset] = schemas.unset,
        semester: typing.Union[MetaOapg.properties.semester, str, schemas.Unset] = schemas.unset,
        number: typing.Union[MetaOapg.properties.number, str, schemas.Unset] = schemas.unset,
        seats: typing.Union[MetaOapg.properties.seats, str, schemas.Unset] = schemas.unset,
        meetings: typing.Union[MetaOapg.properties.meetings, list, tuple, schemas.Unset] = schemas.unset,
        open_seats: typing.Union[MetaOapg.properties.open_seats, str, schemas.Unset] = schemas.unset,
        waitlist: typing.Union[MetaOapg.properties.waitlist, str, schemas.Unset] = schemas.unset,
        instructors: typing.Union[MetaOapg.properties.instructors, list, tuple, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'Section':
        return super().__new__(
            cls,
            *_args,
            course=course,
            section_id=section_id,
            semester=semester,
            number=number,
            seats=seats,
            meetings=meetings,
            open_seats=open_seats,
            waitlist=waitlist,
            instructors=instructors,
            _configuration=_configuration,
            **kwargs,
        )

from umd_io.model.meeting import Meeting
