# coding: utf-8

"""
    umd.io

    Welcome to umd.io, the open-source API for University of Maryland data. If you are building a University data-focused app, hack, or project, you’re in the right place. This site will walk you through basic API use and document all supported API calls.  umd.io is a GETful API. It follows RESTful conventions, but for now, you can only get data – you can’t create, update, or destroy.  We're now in version 1! We might add new endpoints or more data to existing responses, but we won't remove anything without a major version change.  If you're looking for the v0 docs, you can find them at https://docs.umd.io/. Please note that v0 is deprecated. It will continue to be supported until at least 2021, but will get no further feature updates, and will eventually be discontinued.  We are actively looking for contributors! Tweet, email, or otherwise get in touch with us.  # noqa: E501

    The version of the OpenAPI document: 1.0.0 Beta
    Contact: hi@umd.io
    Generated by: https://openapi-generator.tech
"""

from umd_io.paths.courses_list.get import GetCourseList
from umd_io.paths.courses_course_ids_sections_section_ids.get import GetCourseSectionsById
from umd_io.paths.courses.get import GetCourses
from umd_io.paths.courses_course_ids.get import GetCoursesById
from umd_io.paths.courses_departments.get import GetDepartments
from umd_io.paths.courses_sections.get import GetSections
from umd_io.paths.courses_sections_section_ids.get import GetSectionsByIds
from umd_io.paths.courses_course_ids_sections.get import GetSectionsForCourse
from umd_io.paths.courses_semesters.get import GetSemesters


class CoursesApi(
    GetCourseList,
    GetCourseSectionsById,
    GetCourses,
    GetCoursesById,
    GetDepartments,
    GetSections,
    GetSectionsByIds,
    GetSectionsForCourse,
    GetSemesters,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
